// MTG Card Image Imports
// This file imports all MTG card images for proper bundling in GitHub Pages deployment
// Auto-generated by scripts/generate-mtg-index.js - DO NOT EDIT MANUALLY

import a25198BlightningImg from './a25-198-blightning.jpg';
import blb113SinisterMonolith1Img from './blb-113-sinister-monolith-1.jpg';
import blb113SinisterMonolithImg from './blb-113-sinister-monolith.jpg';
import blb12EssenceChannelerImg from './blb-12-essence-channeler.jpg';
import blb131CoruscationMageImg from './blb-131-coruscation-mage.jpg';
import blb139HearthbornBattlerImg from './blb-139-hearthborn-battler.jpg';
import blb207CamelliaTheSeedmiserImg from './blb-207-camellia-the-seedmiser.jpg';
import blb214GevScaledScorchImg from './blb-214-gev-scaled-scorch.jpg';
import blb223LunarConvocationImg from './blb-223-lunar-convocation.jpg';
import blb235TempestAnglerImg from './blb-235-tempest-angler.jpg';
import blb239VrenTheRelentlessImg from './blb-239-vren-the-relentless.jpg';
import blb242ZoralineCosmosCallerImg from './blb-242-zoraline-cosmos-caller.jpg';
import blb290RottenmouthViperImg from './blb-290-rottenmouth-viper.jpg';
import blb316FestivalOfEmbersImg from './blb-316-festival-of-embers.jpg';
import blb366LunarConvocationImg from './blb-366-lunar-convocation.jpg';
import blb383FellImg from './blb-383-fell.jpg';
import blb48EddymurkCrabImg from './blb-48-eddymurk-crab.jpg';
import blb90DarkstarAugurImg from './blb-90-darkstar-augur.jpg';
import blb98HuskbursterSwarmImg from './blb-98-huskburster-swarm.jpg';
import c13199MayaelTheAnimaImg from './c13-199-mayael-the-anima.jpg';
import c20130CairnWandererImg from './c20-130-cairn-wanderer.jpg';
import cmm389HauntedCloakImg from './cmm-389-haunted-cloak.jpg';
import dbl254JackOLanternImg from './dbl-254-jack-o-lantern.jpg';
import dft213MendicantCoreGuidelightImg from './dft-213-mendicant-core-guidelight.jpg';
import dsc1AminatouVeilPiercerImg from './dsc-1-aminatou-veil-piercer.jpg';
import dsc7WinterCynicalOpportunistImg from './dsc-7-winter-cynical-opportunist.jpg';
import dsk120ValgavothTerrorEaterImg from './dsk-120-valgavoth-terror-eater.jpg';
import dsk208ArabellaAbandonedDollImg from './dsk-208-arabella-abandoned-doll.jpg';
import dsk217InquisitiveGlimmerImg from './dsk-217-inquisitive-glimmer.jpg';
import dsk238VictorValgavothSSeneschalImg from './dsk-238-victor-valgavoth-s-seneschal.jpg';
import dsk241ZimoneAllQuestioningImg from './dsk-241-zimone-all-questioning.jpg';
import dsk26ReluctantRoleModelImg from './dsk-26-reluctant-role-model.jpg';
import dsk262LakesideShackImg from './dsk-262-lakeside-shack.jpg';
import dsk352ValgavothTerrorEaterImg from './dsk-352-valgavoth-terror-eater.jpg';
import dsk40VeteranSurvivorImg from './dsk-40-veteran-survivor.jpg';
import dsk6EnduringInnocenceImg from './dsk-6-enduring-innocence.jpg';
import dsk68OverlordOfTheFloodpitsImg from './dsk-68-overlord-of-the-floodpits.jpg';
import eoc2InspiritFlagshipVesselImg from './eoc-2-inspirit-flagship-vessel.jpg';
import eve62StigmaLasherImg from './eve-62-stigma-lasher.jpg';
import fdn107MossbornHydraImg from './fdn-107-mossborn-hydra.jpg';
import fdn234VivienReidImg from './fdn-234-vivien-reid.jpg';
import fdn30ArchmageOfRunesImg from './fdn-30-archmage-of-runes.jpg';
import fdn307HighFaeTricksterImg from './fdn-307-high-fae-trickster.jpg';
import fdn521DeathBaronImg from './fdn-521-death-baron.jpg';
import fdn642PredatorOozeImg from './fdn-642-predator-ooze.jpg';
import fdn67RevengeOfTheRatsImg from './fdn-67-revenge-of-the-rats.jpg';
import fdn671DarksteelColossusImg from './fdn-671-darksteel-colossus.jpg';
import fdn92RiteOfTheDragoncallerImg from './fdn-92-rite-of-the-dragoncaller.jpg';
import inr257ChaliceOfDeathImg from './inr-257-chalice-of-death.jpg';
import inr257ChaliceOfLifeImg from './inr-257-chalice-of-life.jpg';
import jmp450DinrovaHorrorImg from './jmp-450-dinrova-horror.jpg';
import lci116RampagingSpiketailImg from './lci-116-rampaging-spiketail.jpg';
import ltr756TheShireImg from './ltr-756-the-shire.jpg';
import m1115GoldenglowMothImg from './m11-15-goldenglow-moth.jpg';
import mh2151ChatterfangSquirrelGeneralImg from './mh2-151-chatterfang-squirrel-general.jpg';
import mic1LeinoreAutumnSovereignImg from './mic-1-leinore-autumn-sovereign.jpg';
import mic116EndlessRanksOfTheDeadImg from './mic-116-endless-ranks-of-the-dead.jpg';
import mic148DiregrafCaptainImg from './mic-148-diregraf-captain.jpg';
import mm225MirranCrusaderImg from './mm2-25-mirran-crusader.jpg';
import mma13ElspethKnightErrantImg from './mma-13-elspeth-knight-errant.jpg';
import neo234SatoruUmezawaImg from './neo-234-satoru-umezawa.jpg';
import one318GlissaSunslayerImg from './one-318-glissa-sunslayer.jpg';
import rvr140ForcedAdaptationImg from './rvr-140-forced-adaptation.jpg';
import sld1623VorinclexVoiceOfHungerImg from './sld-1623-vorinclex-voice-of-hunger.jpg';
import sld76AthreosGodOfPassageImg from './sld-76-athreos-god-of-passage.jpg';
import snc204MrOrfeoTheBoulderImg from './snc-204-mr-orfeo-the-boulder.jpg';
import snc301CormelaGlamourThiefImg from './snc-301-cormela-glamour-thief.jpg';
import snc357WaterfrontDistrictImg from './snc-357-waterfront-district.jpg';
import tsr262AkromaSMemorialImg from './tsr-262-akroma-s-memorial.jpg';
import war217SorinVengefulBloodlordImg from './war-217-sorin-vengeful-bloodlord.jpg';
import woe178NightOfTheSweetsRevengeImg from './woe-178-night-of-the-sweets-revenge.jpg';
import woe198WelcomeToSweettoothImg from './woe-198-welcome-to-sweettooth.jpg';

// Export as a map for easy lookup by filename
export const mtgCardImages: { [key: string]: string } = {
  'a25-198-blightning': a25198BlightningImg,
  'blb-113-sinister-monolith-1': blb113SinisterMonolith1Img,
  'blb-113-sinister-monolith': blb113SinisterMonolithImg,
  'blb-12-essence-channeler': blb12EssenceChannelerImg,
  'blb-131-coruscation-mage': blb131CoruscationMageImg,
  'blb-139-hearthborn-battler': blb139HearthbornBattlerImg,
  'blb-207-camellia-the-seedmiser': blb207CamelliaTheSeedmiserImg,
  'blb-214-gev-scaled-scorch': blb214GevScaledScorchImg,
  'blb-223-lunar-convocation': blb223LunarConvocationImg,
  'blb-235-tempest-angler': blb235TempestAnglerImg,
  'blb-239-vren-the-relentless': blb239VrenTheRelentlessImg,
  'blb-242-zoraline-cosmos-caller': blb242ZoralineCosmosCallerImg,
  'blb-290-rottenmouth-viper': blb290RottenmouthViperImg,
  'blb-316-festival-of-embers': blb316FestivalOfEmbersImg,
  'blb-366-lunar-convocation': blb366LunarConvocationImg,
  'blb-383-fell': blb383FellImg,
  'blb-48-eddymurk-crab': blb48EddymurkCrabImg,
  'blb-90-darkstar-augur': blb90DarkstarAugurImg,
  'blb-98-huskburster-swarm': blb98HuskbursterSwarmImg,
  'c13-199-mayael-the-anima': c13199MayaelTheAnimaImg,
  'c20-130-cairn-wanderer': c20130CairnWandererImg,
  'cmm-389-haunted-cloak': cmm389HauntedCloakImg,
  'dbl-254-jack-o-lantern': dbl254JackOLanternImg,
  'dft-213-mendicant-core-guidelight': dft213MendicantCoreGuidelightImg,
  'dsc-1-aminatou-veil-piercer': dsc1AminatouVeilPiercerImg,
  'dsc-7-winter-cynical-opportunist': dsc7WinterCynicalOpportunistImg,
  'dsk-120-valgavoth-terror-eater': dsk120ValgavothTerrorEaterImg,
  'dsk-208-arabella-abandoned-doll': dsk208ArabellaAbandonedDollImg,
  'dsk-217-inquisitive-glimmer': dsk217InquisitiveGlimmerImg,
  'dsk-238-victor-valgavoth-s-seneschal': dsk238VictorValgavothSSeneschalImg,
  'dsk-241-zimone-all-questioning': dsk241ZimoneAllQuestioningImg,
  'dsk-26-reluctant-role-model': dsk26ReluctantRoleModelImg,
  'dsk-262-lakeside-shack': dsk262LakesideShackImg,
  'dsk-352-valgavoth-terror-eater': dsk352ValgavothTerrorEaterImg,
  'dsk-40-veteran-survivor': dsk40VeteranSurvivorImg,
  'dsk-6-enduring-innocence': dsk6EnduringInnocenceImg,
  'dsk-68-overlord-of-the-floodpits': dsk68OverlordOfTheFloodpitsImg,
  'eoc-2-inspirit-flagship-vessel': eoc2InspiritFlagshipVesselImg,
  'eve-62-stigma-lasher': eve62StigmaLasherImg,
  'fdn-107-mossborn-hydra': fdn107MossbornHydraImg,
  'fdn-234-vivien-reid': fdn234VivienReidImg,
  'fdn-30-archmage-of-runes': fdn30ArchmageOfRunesImg,
  'fdn-307-high-fae-trickster': fdn307HighFaeTricksterImg,
  'fdn-521-death-baron': fdn521DeathBaronImg,
  'fdn-642-predator-ooze': fdn642PredatorOozeImg,
  'fdn-67-revenge-of-the-rats': fdn67RevengeOfTheRatsImg,
  'fdn-671-darksteel-colossus': fdn671DarksteelColossusImg,
  'fdn-92-rite-of-the-dragoncaller': fdn92RiteOfTheDragoncallerImg,
  'inr-257-chalice-of-death': inr257ChaliceOfDeathImg,
  'inr-257-chalice-of-life': inr257ChaliceOfLifeImg,
  'jmp-450-dinrova-horror': jmp450DinrovaHorrorImg,
  'lci-116-rampaging-spiketail': lci116RampagingSpiketailImg,
  'ltr-756-the-shire': ltr756TheShireImg,
  'm11-15-goldenglow-moth': m1115GoldenglowMothImg,
  'mh2-151-chatterfang-squirrel-general': mh2151ChatterfangSquirrelGeneralImg,
  'mic-1-leinore-autumn-sovereign': mic1LeinoreAutumnSovereignImg,
  'mic-116-endless-ranks-of-the-dead': mic116EndlessRanksOfTheDeadImg,
  'mic-148-diregraf-captain': mic148DiregrafCaptainImg,
  'mm2-25-mirran-crusader': mm225MirranCrusaderImg,
  'mma-13-elspeth-knight-errant': mma13ElspethKnightErrantImg,
  'neo-234-satoru-umezawa': neo234SatoruUmezawaImg,
  'one-318-glissa-sunslayer': one318GlissaSunslayerImg,
  'rvr-140-forced-adaptation': rvr140ForcedAdaptationImg,
  'sld-1623-vorinclex-voice-of-hunger': sld1623VorinclexVoiceOfHungerImg,
  'sld-76-athreos-god-of-passage': sld76AthreosGodOfPassageImg,
  'snc-204-mr-orfeo-the-boulder': snc204MrOrfeoTheBoulderImg,
  'snc-301-cormela-glamour-thief': snc301CormelaGlamourThiefImg,
  'snc-357-waterfront-district': snc357WaterfrontDistrictImg,
  'tsr-262-akroma-s-memorial': tsr262AkromaSMemorialImg,
  'war-217-sorin-vengeful-bloodlord': war217SorinVengefulBloodlordImg,
  'woe-178-night-of-the-sweets-revenge': woe178NightOfTheSweetsRevengeImg,
  'woe-198-welcome-to-sweettooth': woe198WelcomeToSweettoothImg,
};
